/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import conexionconbasededatos.Ordenador;
import database.Funciones;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arturo
 */
public class InterfazBaseDatos extends javax.swing.JFrame{

    DefaultTableModel tab;

    /**
     * Creates new form InterfazBaseDatos
     */
    public InterfazBaseDatos(){
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Ventana de control");
        tab=(DefaultTableModel) tOrdenadores.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        ltitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tOrdenadores = new javax.swing.JTable();
        bVisualizar = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(0, 102, 102));

        ltitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ltitulo.setText("Datos de ordenadores");

        tOrdenadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Marca", "Modelo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tOrdenadores);
        if (tOrdenadores.getColumnModel().getColumnCount() > 0) {
            tOrdenadores.getColumnModel().getColumn(0).setResizable(false);
            tOrdenadores.getColumnModel().getColumn(1).setResizable(false);
            tOrdenadores.getColumnModel().getColumn(2).setResizable(false);
            tOrdenadores.getColumnModel().getColumn(3).setResizable(false);
            tOrdenadores.getColumnModel().getColumn(4).setResizable(false);
        }

        bVisualizar.setBackground(new java.awt.Color(0, 0, 255));
        bVisualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        bVisualizar.setText("Visualizar Datos");
        bVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisualizarActionPerformed(evt);
            }
        });

        bAdd.setBackground(new java.awt.Color(255, 0, 255));
        bAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bAdd.setForeground(new java.awt.Color(255, 255, 255));
        bAdd.setText("Añadir Entrada");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bUpdate.setBackground(new java.awt.Color(255, 102, 0));
        bUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bUpdate.setForeground(new java.awt.Color(255, 255, 255));
        bUpdate.setText("Modificar Entrada");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        bBorrar.setBackground(new java.awt.Color(255, 0, 0));
        bBorrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bBorrar.setForeground(new java.awt.Color(255, 255, 255));
        bBorrar.setText("Borrar Entrada");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bSearch.setBackground(new java.awt.Color(0, 204, 0));
        bSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bSearch.setForeground(new java.awt.Color(255, 255, 255));
        bSearch.setText("Buscar");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(ltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bVisualizar)
                        .addGap(18, 18, 18)
                        .addComponent(bAdd)
                        .addGap(18, 18, 18)
                        .addComponent(bSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(bBorrar)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ltitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVisualizar)
                    .addComponent(bAdd)
                    .addComponent(bUpdate)
                    .addComponent(bBorrar)
                    .addComponent(bSearch))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        VentanaAñadir va=new VentanaAñadir();
    }//GEN-LAST:event_bAddActionPerformed

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        VentanaBusqueda vBusq= new VentanaBusqueda();
    }//GEN-LAST:event_bSearchActionPerformed

    private void bVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisualizarActionPerformed
        for(int i=0; i<tab.getRowCount(); i++){
            tab.removeRow(i);
            tab.setRowCount(0);
        }
        Funciones.selectAll();
        Object ob[]=null;
        for(int i=0; i<Ordenador.ordenadores.size(); i++){
            System.out.println(Ordenador.ordenadores.get(i));
            tab.addRow(ob);
            tab.setValueAt(Ordenador.ordenadores.get(i).getCodigo(), i, 0);
            tab.setValueAt(Ordenador.ordenadores.get(i).getNombre(), i, 1);
            tab.setValueAt(Ordenador.ordenadores.get(i).getMarca(), i, 2);
            tab.setValueAt(Ordenador.ordenadores.get(i).getModelo(), i, 3);
            tab.setValueAt(Ordenador.ordenadores.get(i).getPrecio(), i, 4);
        }
        //bVisualizar.setEnabled(false);
        
    }//GEN-LAST:event_bVisualizarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        VentanaBorrar b=new VentanaBorrar();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        VentanaModificar vm= new VentanaModificar();
    }//GEN-LAST:event_bUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
                if("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch(ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(InterfazBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch(InstantiationException ex){
            java.util.logging.Logger.getLogger(InterfazBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch(IllegalAccessException ex){
            java.util.logging.Logger.getLogger(InterfazBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch(javax.swing.UnsupportedLookAndFeelException ex){
            java.util.logging.Logger.getLogger(InterfazBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                new InterfazBaseDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bSearch;
    private javax.swing.JButton bUpdate;
    private javax.swing.JButton bVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tOrdenadores;
    // End of variables declaration//GEN-END:variables
}
